apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  type: NodePort
  ports:
    - port: 9080
      name: http
  selector:
    app: productpage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  selector:
    matchLabels:
      app: productpage
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      serviceAccountName: productpage
      containers:
        - name: productpage
          image: istio/examples-bookinfo-productpage-v1:1.10.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 9080
          readinessProbe:
            httpGet:
              path: /health
              port: 9080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: productpage
          ports:
            - containerPort: 9080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: productpage
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
    - http:
        paths:
          - path: "/*"
            pathType: ImplementationSpecific
            backend:
              service:
                name: productpage
                port:
                  number: 9080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: productpage
data:
  DETAILS_HOSTNAME: details
  RATINGS_HOSTNAME: ratings
  REVIEWS_HOSTNAME: review
