### Reviews
apiVersion: specs.smi-spec.io/v1alpha3
kind: HTTPRouteGroup
metadata:
  name: everything
spec:
  matches:
    - name: all
      pathRegex: ".*"
      methods: ["*"]
---
apiVersion: specs.smi-spec.io/v1alpha3
kind: HTTPRouteGroup
metadata:
  name: metrics
spec:
  matches:
    - name: metrics
      pathRegex: "/metrics"
      methods: ["GET"]
---
apiVersion: access.smi-spec.io/v1alpha2
kind: TrafficTarget
metadata:
  name: reviews-all
spec:
  destination:
    kind: ServiceAccount
    name: reviews
    namespace: default
  rules:
    - kind: HTTPRouteGroup
      name: everything
  sources:
    - kind: ServiceAccount
      name: productpage
      namespace: default
---
apiVersion: access.smi-spec.io/v1alpha2
kind: TrafficTarget
metadata:
  name: ratings-all
spec:
  destination:
    kind: ServiceAccount
    name: ratings
    namespace: default
  rules:
    - kind: HTTPRouteGroup
      name: everything
  sources:
    - kind: ServiceAccount
      name: reviews
      namespace: default

# curl http://details.default.traefik.mesh:9080
